### ISSUE TITLE
Unexpected error on Plakar UI

### ISSUE THREAD

**Issue by poolpOrg** [PlakarKorp/plakar#121]
symlink pages are broken, to reproduce (on macOS):

$ plakar backup /private/etc
$ plakar ui

click on /private/etc/aliases

```
TypeError: Failed to fetch

TypeError: Failed to fetch
    at iu (http://localhost:55375/assets/index-WRxjD4Kc.js:214:12901)
    at $w (http://localhost:55375/assets/index-WRxjD4Kc.js:217:92451)
    at Object.loader (http://localhost:55375/assets/index-WRxjD4Kc.js:217:105479)
    at O (http://localhost:55375/assets/index-WRxjD4Kc.js:33:26591)
    at http://localhost:55375/assets/index-WRxjD4Kc.js:33:27546
    at http://localhost:55375/assets/index-WRxjD4Kc.js:33:27726
    at Array.forEach (<anonymous>)
    at http://localhost:55375/assets/index-WRxjD4Kc.js:33:25277```

**Comment by poolpOrg** [comment]
fixed
